# Generated by Django 3.0.7 on 2020-10-29 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metasat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(blank=True, max_length=4, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('metasatelement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metasat.Element')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crosswalk.ExternalSchema')),
            ],
            options={
                'ordering': ('metasatelement',),
            },
        ),
    ]
