# Generated by Django 3.0.3 on 2020-03-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='synonym',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='element',
            name='segment',
        ),
        migrations.AddField(
            model_name='element',
            name='segment',
            field=models.ManyToManyField(blank=True, to='metasat.Segment'),
        ),
    ]
