# Generated by Django 3.0.3 on 2020-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasat', '0002_auto_20200309_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
