# Generated by Django 3.0.3 on 2020-03-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasat', '0003_element_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
