# Generated by Django 3.0.4 on 2020-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasat', '0004_auto_20200313_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='schematype',
        ),
        migrations.RemoveField(
            model_name='element',
            name='segment',
        ),
        migrations.AddField(
            model_name='element',
            name='term',
            field=models.CharField(default='term', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='SchemaType',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
