# Generated by Django 3.0.4 on 2020-05-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasat', '0005_auto_20200501_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
