# Generated by Django 3.0.4 on 2020-05-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metasat', '0006_auto_20200508_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metasat.ElementFamily'),
        ),
    ]
