# Generated by Django 3.0.4 on 2020-05-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasat', '0008_auto_20200526_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='family',
        ),
        migrations.AddField(
            model_name='element',
            name='family',
            field=models.ManyToManyField(blank=True, null=True, to='metasat.ElementFamily'),
        ),
        migrations.RemoveField(
            model_name='element',
            name='segment',
        ),
        migrations.AddField(
            model_name='element',
            name='segment',
            field=models.ManyToManyField(blank=True, null=True, to='metasat.Segment'),
        ),
    ]
