# Generated by Django 3.0.4 on 2020-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasat', '0009_auto_20200526_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='family',
            field=models.ManyToManyField(blank=True, to='metasat.ElementFamily'),
        ),
        migrations.AlterField(
            model_name='element',
            name='segment',
            field=models.ManyToManyField(blank=True, to='metasat.Segment'),
        ),
    ]
